import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

// All bilingual UI strings
export const translations = {
  en: {
    // Common
    home: 'Home',
    about: 'About',
    deities: 'Deities',
    darshan: 'Darshan',
    vazhipadu: 'Vazhipadu',
    festivals: 'Festivals',
    gallery: 'Gallery',
    kanikka: 'E-Kanikka',
    contact: 'Contact',

    // Navbar
    templeNameEn: 'Bharanatheril Sree Bhadra Bhagavathy Temple',
    templeNameMl: 'Bharanatheril Sree Bhadra Bhagavathy Temple',
    nadaOpen: 'Nada Open',
    nadaClosed: 'Nada Closed',
    ringBell: 'Ring Bell',
    meditation: 'Meditation',
    meditationOn: 'Meditation On',
    bookVazhipadu: 'Book Offering',
    eKanikka: 'E-Kanikka',

    // Hero
    sacredMantra: 'Om Sree Bhadrakalyai Namah',
    templeLocation: 'Thurayilkunnu, Karunagappally, Kollam',
    bookVazhipaduFull: 'Book Vazhipadu',
    darshanTimings: 'Darshan Timings',
    annadanam: 'E-Kanikka / Annadanam',
    templebell: 'Temple Bell',
    sacredConch: 'Sacred Conch',
    heroTitlePrimary: 'Bharanatheril Sree Bhadra Bhagavathy Temple',
    heroTitleSecondary: 'Bharanatheril Sree Bhadra Bhagavathy Temple',
    slokaMeaning: 'Salutations to You, O Auspicious Mother, who brings all that is good, who fulfills all sacred desires, the protector and refuge, three-eyed Gauri, Narayani, we bow to Thee.',

    // Home Page
    morningDarshan: 'Morning Darshan',
    eveningDarshan: 'Evening & Deeparadhana',
    locationLabel: 'Location',
    viewFullTimings: 'Full Schedule',
    aboutHeadline: 'Sacred Abode of Motherly Protection & Blessings',
    readHistory: 'Read Temple History',
    viewDeities: 'View All Deities',
    bookNow: 'Book Now',
    viewFullCatalog: 'View Full Offering Catalog',
    donateNow: 'Donate Now',
    viewFestivalSchedule: 'Festival Schedule',
    festivalDonate: 'Festival Kanikka',
    viewAllShrines: 'View All 5 Shrines',
    offeringsHeadline: 'Sacred Offerings for Divine Grace',
    centuriesOfGrace: 'Centuries of Divine Grace',
    sacredAbodeBhadrakali: 'The Sacred Abode of Bhadrakali',
    welcomeDescText: 'Gracefully situated on the sacred high mound of Thurayilkunnu in Karunagappally, Bharanatheril Sree Bhadra Bhagavathy Temple is an ancient spiritual haven where thousands of devotees seek solace, protection, and boundless grace.',
    welcomePt1: 'Traditional Kerala Vastu Thachu-shastra Srikovil',
    welcomePt2: 'Sacred Sarpa Kavu with ancient sacred flora',
    welcomePt3: 'Daily Annadanam & Nithya Pushpanjali rituals',
    presidingSubShrines: 'Presiding Deities & Sub-Shrines',
    sacredShrinesTitle: 'Sacred Shrines',
    devotionalOfferings: 'Devotional Offerings',
    featuredVazhipadu: 'Featured Vazhipadu Offerings',
    vazhipaduSectionDesc: 'Book sacred offerings online with your birth star (Nakshathram) and receive divine blessings.',
    grandAnnualFestivalTitle: 'Grand Annual Festival',
    annualBharaniTitle: 'Annual Bharani Mahotsavam',
    festivalSubDesc: 'Kumbham/Meenam – Thalappoli, Chenda Melam & Guruthi',
    festivalHomeSummary: 'Join thousands of pilgrims in the grandest celebration at Thurayilkunnu. Experience majestic caparisoned elephants, Thalappoli processions, traditional Chenda Melam, and midnight Guruthi Tharpana.',
    annadanamLabel: 'Nithya Annadanam & E-Kanikka',
    annadanamTitle: 'Annadanam Mahādānam • Sacred Food Offering',
    annadanamDesc: 'Support daily prasada oottu, festival celebrations, and temple development. Every contribution brings immense blessings.',

    // About
    historyTab: 'History & Lore',
    architectureTab: 'Architecture',
    trustTab: 'Trust & Admin',
    etiquetteTab: 'Etiquette & Rules',
    divineOrigin: 'Divine Origin & Sacred Lore',
    divinePresenceTitle: 'The Divine Presence of Bhadrakali at Thurayilkunnu',
    divinePresenceSubtitle: 'Centuries of Motherly Blessings & Spiritual Radiance',
    quoteText: '"The shower of divine blessings from Sree Bhadrakali has been flowing across the sacred land of Thurayilkunnu for generations."',
    quoteAuthor: '— Devotional Lore Tradition',
    shieldTitle: 'Divine Shield of Protection',
    shieldDesc: 'Mother Bhadrakali protects devotees from unseen perils, ailments, and fears.',
    wishesTitle: 'Fulfillment of Prayers',
    wishesDesc: 'Devotees witness heartfelt prayers for health, marriage, and prosperity fulfilled.',
    templeSanctumLocation: 'Thurayilkunnu, Karunagappally',
    quickFacts: 'Temple Quick Facts',
    presidingDeityLabel: 'Presiding Deity',
    auspiciousStarLabel: 'Auspicious Star',
    annualFestivalLabel: 'Annual Festival',
    srikovilTitle: 'Srikovil Sanctum',
    srikovilDesc: 'Built according to ancient Kerala Thachu-shastra (Vastu Vidya). The square sanctum retains divine energy with natural laterite stone and copper roofing, housing the radiant Bhadrakali idol adorned with sacred jewels.',
    chuttambalamTitle: 'Chuttambalam & Aanapanthal',
    chuttambalamDesc: 'Surrounding corridors adorned with rows of traditional oil lamps (Deepasthambham) that come alive with radiant golden warmth during twilight Deeparadhana. The Aanapanthal accommodates devotees during festival processions and melam.',
    sarpaKavuTitle: 'Sacred Serpent Grove (Sarpa Kavu)',
    sarpaKavuDesc: 'A lush, ancient sacred grove preserving indigenous medicinal trees and natural flora. Devotees offer Noorum Palum and Manjal Podi at the granite shrines of Nagaraja and Nagayakshi for ancestral and health blessings.',
    thidappallyTitle: 'Thidappally & Oottupura',
    thidappallyDesc: 'The sanctified temple kitchen where holy Kadumpayasam, Payasam, and nivedyams are prepared strictly adhering to Kerala Vedic culinary rituals with pure ghee, jaggery, and tender coconut water.',
    trustIntroTitle: 'Bharanatheril Sree Bhadra Bhagavathy Temple Trust',
    trustIntroDesc: 'The temple is administered by a registered devotional trust dedicated to preserving ancient customs, maintaining holy premises, organizing annual festivals, and upholding community welfare through daily Annadanam.',
    trustRegLabel: 'Trust Registration',
    trustRegVal: 'Registered Public Religious Trust',
    trustOfficeLabel: 'Administrative Office',
    contactPhoneLabel: 'Contact Phone',
    officialBankDetails: 'Official Bank Details for Donations',
    donateToTrust: 'Donate to Trust',
    contactOffice: 'Contact Office',
    dressCodeTitle: 'Temple Dress Code',
    dressCodeIntro: 'Devotees are requested to maintain traditional decorum while entering the Chuttambalam:',
    dressMenLabel: 'Men',
    dressMenVal: 'Traditional Dhoti (Mundu) / Kerala Kasavu Mundu. Shirts are to be removed before entering the inner sanctum.',
    dressWomenLabel: 'Women',
    dressWomenVal: 'Saree, Kerala Set Mundu, Salwar Kameez, or traditional modest attire.',
    dressKidsLabel: 'Children',
    dressKidsVal: 'Traditional comfortable and respectful clothing.',
    customsTitle: 'Temple Customs & Etiquette',
    customs1: 'Please remove footwear at the designated counter outside the temple gate.',
    customs2: 'Circumambulate the Srikovil (Pradakshinam) with mindful peace and chanting.',
    customs3: 'Photography and videography inside the inner sanctum (Srikovil) are strictly prohibited.',
    customs4: 'Mobile phones must be kept in silent mode within temple premises.',
    customs5: 'Maintain cleanliness and protect the sacred flora of Sarpa Kavu.',
    planVisit: 'Planning your visit? Check daily darshan timings and book sacred poojas in advance.',

    // Deities
    specialDaysLabel: 'Special Days',
    keyOfferingsLabel: 'Key Offerings',
    bookOffering: 'Book Offering',
    darshanTimingsBtn: 'Darshan Timings',
    allShrines: 'All Shrines',
    deitySplendor: 'Divine Deity Splendor',
    dhyanaSloka: 'Meditation Verse (Dhyana Sloka)',
    bookOfferingsForDeity: 'Book Offerings',
    specialLabel: 'Special:',

    // Darshan
    templeOpen: 'Temple Open',
    templeClosed: 'Temple Closed',
    darshanAvailable: 'Darshan Available for Devotees',
    nextDarshanSoon: 'Next Darshan Timings Soon',
    morningSession: 'Morning',
    eveningSession: 'Evening & Night',
    specialPoojasDays: 'Special Pooja Days & Observances',
    monthlyObservances: 'Monthly Observances',
    bookSpecialPoojaBirthStar: 'Book Special Poojas on Your Birth Star',
    bookSpecialPoojaDesc: 'Advance booking for daily archana, pushpanjali, and payasa nivedyam offerings.',
    timeRemClosesAfternoon: (h, m) => `Sanctum closes for afternoon in ${h > 0 ? `${h}h ` : ''}${m}m`,
    timeRemClosesNight: (h, m) => `Sanctum closes for night in ${h > 0 ? `${h}h ` : ''}${m}m`,
    timeRemOpensMorning: (h, m) => `Morning sanctum opens in ${h > 0 ? `${h}h ` : ''}${m}m (5:30 AM)`,
    timeRemOpensEvening: (h, m) => `Evening sanctum opens in ${h > 0 ? `${h}h ` : ''}${m}m (5:00 PM)`,
    timeRemOpensTomorrow: 'Sanctum opens tomorrow morning at 5:30 AM',

    // Vazhipadu
    searchPlaceholder: 'Search pooja (e.g. Kadumpayasam, Pushpanjali, Ganapathi Homam)...',
    allDeities: 'All Deities',
    showingOfferings: 'Showing',
    divineOfferings: 'divine offerings',
    resetFilters: 'Reset Filters',
    poojaCart: 'Pooja Cart',
    cartEmpty: 'Your pooja cart is empty.',
    cartEmptyHint: 'Select offerings from the catalog to proceed with your birth star booking.',
    totalAmount: 'Total Amount',
    proceedBooking: 'Proceed to Booking',
    confirmBooking: 'Confirm Booking',
    devoteeName: 'Devotee Name',
    birthStar: 'Birth Star (Nakshathram)',
    poojaDate: 'Pooja Date',
    mobileNumber: 'Mobile Number',
    emailAddress: 'Email Address',
    specialSankalpam: 'Special Sankalpam / Prayer (Optional)',
    postalPrasadam: 'Send Prasadam by Post / Courier',
    postalAddress: 'Complete Postal Address with Pincode',
    paymentMode: 'Payment Mode',
    upiPayment: 'Direct Temple UPI / Google Pay / PhonePe',
    counterPayment: 'Pay at Temple Counter upon Arrival',
    printReceipt: 'Print Sacred Receipt',
    close: 'Close & Return',
    noOfferingsMatch: 'No vazhipadu offerings match your current search.',
    clearAllFilters: 'Clear All Filters',
    bookingDetails: 'Devotee Booking Details',
    bookingToken: 'BOOKING TOKEN',
    devoteeLabel: 'Devotee:',
    starLabel: 'Nakshathram:',
    dateLabel: 'Pooja Date:',
    phoneLabel: 'Phone:',
    paymentModeLabel: 'Payment Mode:',
    bookedAtLabel: 'Booked At:',
    poojaOfferingHeader: 'Pooja Offering',
    deityHeader: 'Deity',
    qtyHeader: 'Qty',
    amountHeader: 'Amount',
    totalPaidPayable: 'Total Amount Paid / Payable:',
    postalPrasadamAddr: 'Postal Prasadam Address:',
    officialUpiHint: 'Please show this token screenshot / receipt at the temple vazhipadu counter.',

    // Festivals
    annualFestival: 'Annual Grand Festival',
    donateFestival: 'Donate for Festival',
    bookFestivalOffering: 'Book Festival Pooja',
    festivalsHighlights: 'Highlights',
    sponsorDay: 'Sponsor a Day',
    festivalSponsorship: 'Festival Seva & Annadanam Participation',
    festivalSponsorshipDesc: 'Devotees can sponsor holy days during the annual festival, including Annadanam for thousands of pilgrims, Thalappoli lamps, decorative illuminations, and pushpanjali.',
    bookPoojas: 'Book Poojas',

    // Gallery
    allVisuals: 'All Visuals',
    sanctumCat: 'Sanctum',
    festivalsCat: 'Festivals',
    sarpaKavuCat: 'Sarpa Kavu',
    architectureCat: 'Architecture',

    // Kanikka/Donation
    annadanamScheme: 'Nithya Annadanam Scheme',
    renovationScheme: 'Temple Renovation & Sreekovil Fund',
    deepamScheme: 'Nitya Deepam & Oil Offering Fund',
    generalScheme: 'General Temple E-Kanikka',
    customAmount: 'Enter other custom amount',
    donorName: 'Devotee / Donor Name',
    copyBankDetails: 'Copy Bank Account Details',
    bankDetailsCopied: 'Bank Details Copied!',
    directUpi: 'Direct UPI Payment',
    taxNote: 'Donations to Bharanatheril Temple Trust are eligible for tax benefits under Section 80G.',
    proceedDonate: 'Proceed to Donate',
    offeringAmountAndDetails: 'Offering Amount & Devotee Details',
    selectAmountHint: 'Select or enter your desired offering amount:',
    addressState: 'Address / State',
    panCard: 'PAN Card (for 80G Tax Exemption)',
    offeringAmountLabel: 'Offering Amount:',
    officialBankAccount: 'Official Temple Trust Account',
    bankNameLabel: 'Bank Name:',
    branchLabel: 'Branch:',
    accountNameLabel: 'Account Name:',
    accountNumberLabel: 'Account Number:',
    ifscCodeLabel: 'IFSC Code:',
    upiAppsHint: 'Supported on Google Pay, PhonePe, Paytm, BHIM & all UPI apps.',
    eKanikkaReceipt: 'E-KANIKKA RECEIPT',
    blessingQuote: '"May the divine grace and blessings of Bhagavathy always be with you and your family."',
    done: 'Done',

    // Contact
    locationTitle: 'Temple Location',
    phonehelpline: 'Helplines',
    emailAddress2: 'Email',
    officeHours: 'Office Hours',
    howToReach: 'How to Reach Bharanatheril Temple',
    byTrain: 'By Train',
    byBus: 'By Bus',
    byRoad: 'By Road (NH 66)',
    byAir: 'By Air',
    byTrainDesc: 'All major express trains halt at Karunagappally. Auto-rickshaws and taxis are available round-the-clock.',
    byBusDesc: 'Regular KSRTC Superfast, Fast Passenger, and local private buses connect Karunagappally to all major cities.',
    byRoadDesc: 'From NH 66 Karunagappally junction, proceed along the Thurayilkunnu link road directly to the temple gate.',
    byAirDesc: 'Trivandrum International Airport is well connected via NH 66 and train line to Karunagappally.',
    devoteesEnquiry: 'Devotee Enquiry / Prayer Request',
    fullName: 'Full Name',
    mobileNo: 'Mobile Number',
    subject: 'Subject',
    messageLabel: 'Message',
    sendEnquiry: 'Send Enquiry',
    messageSent: 'Message Sent Successfully!',
    messageSentDesc: 'Thank you for reaching out. The temple office will respond shortly. May Devi bless you.',
    templeLocationMap: 'Temple Location Map',
    directionsLabel: 'Directions:',
    travelDirectionsText: 'From Karunagappally town center, proceed along the Thurayilkunnu link road. Auto-rickshaws and local taxis are readily available from Karunagappally KSRTC stand and Railway Station directly to Bharanatheril Temple.',

    // Footer
    quickLinks: 'Quick Links',
    darshanFooter: 'Darshan Timings',
    contactFooter: 'Helpline',
    copyright: `© ${new Date().getFullYear()} Bharanatheril Sree Bhadra Bhagavathy Temple Trust. All Rights Reserved.`,
    footerBlessing: 'Om Sree Bhadrakalyai Namah • May Peace & Auspiciousness Prevail Everywhere',

    // Sections
    sacredShrinesses: 'Sacred Shrines & Divine Presences',
    allShrinesBtn: 'All Shrines at Temple',
    pilgrimage: 'Pilgrimage Guide',
    selected: 'Selected Scheme',
    select: 'Select',

    // Units and Timers
    daysUnit: 'Days',
    hoursUnit: 'Hours',
    minutesUnit: 'Minutes',
    secondsUnit: 'Seconds',
  },

  ml: {
    // Common
    home: 'ഹോം',
    about: 'ക്ഷേത്ര ചരിത്രം',
    deities: 'പ്രതിഷ്ഠകൾ',
    darshan: 'ദർശന സമയം',
    vazhipadu: 'വഴിപാട്',
    festivals: 'ഉത്സവങ്ങൾ',
    gallery: 'ചിത്രശാല',
    kanikka: 'E-കാണിക്ക',
    contact: 'വഴികാട്ടി',

    // Navbar
    templeNameEn: 'ഭരണത്തേരിൽ ശ്രീ ഭദ്ര ഭഗവതി ക്ഷേത്രം',
    templeNameMl: 'Bharanatheril Sree Bhadra Bhagavathy Temple',
    nadaOpen: 'നട തുറന്നിരിക്കുന്നു',
    nadaClosed: 'നട അടച്ചിരിക്കുന്നു',
    ringBell: 'മണി മുഴക്കുക',
    meditation: 'ധ്യാനം',
    meditationOn: 'ധ്യാനം (On)',
    bookVazhipadu: 'വഴിപാട് ബുക്ക് ചെയ്യുക',
    eKanikka: 'E-കാണിക്ക',

    // Hero
    sacredMantra: 'ഓം ശ്രീ ഭദ്രകാള്യൈ നമഃ',
    templeLocation: 'തുറയിൽക്കുന്ന്, കരുനാഗപ്പള്ളി, കൊല്ലം',
    bookVazhipaduFull: 'വഴിപാട് ബുക്കിംഗ്',
    darshanTimings: 'ദർശന സമയം',
    annadanam: 'E-കാണിക്ക / അന്നദാനം',
    templebell: 'മണി മുഴക്കുക',
    sacredConch: 'ശംഖനാദം',
    heroTitlePrimary: 'ഭരണത്തേരിൽ ശ്രീ ഭദ്ര ഭഗവതി ക്ഷേത്രം',
    heroTitleSecondary: 'Bharanatheril Sree Bhadra Bhagavathy Temple',
    slokaMeaning: 'സർവ്വമംഗളദായിനിയും സർവ്വാഭീഷ്ടവരദായിനിയും ശരണാഗതവത്സലയുമായ ത്ര്യംബകയായ ഗൗരി നാരായണി അമ്മയെ ഞങ്ങൾ നമസ്കരിക്കുന്നു.',

    // Home Page
    morningDarshan: 'പ്രഭാത ദർശനം',
    eveningDarshan: 'ദീപാരാധന & അത്താഴ പൂജ',
    locationLabel: 'സന്നിധി സ്ഥാനം',
    viewFullTimings: 'പൂർണ്ണ സമയക്രമം',
    aboutHeadline: 'ഭദ്ര കാളി അമ്മയുടെ ദൈവിക അനുഗ്രഹ സന്നിധി',
    readHistory: 'ക്ഷേത്ര ചരിത്രം വായിക്കുക',
    viewDeities: 'എല്ലാ പ്രതിഷ്ഠകളും',
    bookNow: 'ഓൺലൈൻ ബുക്കിംഗ്',
    viewFullCatalog: 'മുഴുവൻ വഴിപാട് പട്ടിക',
    donateNow: 'കാണിക്ക സമർപ്പിക്കുക',
    viewFestivalSchedule: 'ഉത്സവ വിവരങ്ങൾ',
    festivalDonate: 'ഉത്സവ കാണിക്ക',
    viewAllShrines: 'എല്ലാ 5 സന്നിധികളും',
    offeringsHeadline: 'ദൈവിക അനുഗ്രഹത്തിനുള്ള പവിത്രമായ വഴിപാടുകൾ',
    centuriesOfGrace: 'ദൈവിക അനുഗ്രഹ സന്നിധി',
    sacredAbodeBhadrakali: 'ഭദ്രകാളിയുടെ പുണ്യ സന്നിധി',
    welcomeDescText: 'കരുനാഗപ്പള്ളിയിലെ തുറയിൽക്കുന്നിന്റെ ദൈവിക ഉന്നതിയിൽ സ്ഥിതി ചെയ്യുന്ന ഭരണത്തേരിൽ ശ്രീ ഭദ്ര ഭഗവതി ക്ഷേത്രം, ആയിരക്കണക്കിന് ഭക്തർ ശാന്തിയും, രക്ഷയും, ദൈവ കൃപയും തേടി വരുന്ന ഒരു പുണ്യ സന്നിധാനമാണ്.',
    welcomePt1: 'പരമ്പരാഗത കേരള തച്ചുശാസ്ത്ര ശ്രീകോവിൽ',
    welcomePt2: 'പുരാതന സസ്യങ്ങൾ നിറഞ്ഞ പവിത്ര സർപ്പക്കാവ്',
    welcomePt3: 'നിത്യ അന്നദാനവും പുഷ്പാഞ്ജലി ചടങ്ങുകളും',
    presidingSubShrines: 'പ്രധാന പ്രതിഷ്ഠകളും ഉപദേവതകളും',
    sacredShrinesTitle: 'പവിത്ര ശ്രീകോവിൽ സന്നിധികൾ',
    devotionalOfferings: 'ഭക്തിപൂർവ്വമായ വഴിപാടുകൾ',
    featuredVazhipadu: 'പ്രധാന വഴിപാടുകൾ',
    vazhipaduSectionDesc: 'നിങ്ങളുടെ ജന്മ നക്ഷത്രത്തിൽ ഓൺലൈൻ ബുക്കിംഗ് ചെയ്ത് ദൈവ അനുഗ്രഹം നേടൂ.',
    grandAnnualFestivalTitle: 'വാർഷിക മഹോത്സവം',
    annualBharaniTitle: 'കുംഭ / മീന ഭരണി മഹോത്സവം',
    festivalSubDesc: 'കൊടിയേറ്റ്, തലപ്പൊലി, ചെണ്ട മേളം & ഗുരുതി',
    festivalHomeSummary: 'ആയിരക്കണക്കിന് ഭക്തർ ഒത്തുചേരുന്ന ഭരണിമഹോത്സവത്തിൽ പങ്കെടുക്കൂ. ആനക്കൊമ്പ്, തലപ്പൊലി, ചെണ്ട മേളം, ഗുരുതി തർപ്പണം – ആഘോഷ പ്രൗഢി ഒത്തുചേരുന്ന ഉത്സവം.',
    annadanamLabel: 'നിത്യ അന്നദാനം & E-കാണിക്ക',
    annadanamTitle: 'അന്നദാനം മഹാദാനം',
    annadanamDesc: 'ദൈനംദിന പ്രസാദ ഓട്ടു, ഉത്സവ ആഘോഷങ്ങൾ, ക്ഷേത്ര നവീകരണ പ്രവർത്തനങ്ങൾ എന്നിവ പിന്തുണക്കൂ. ഓരോ സംഭാവനയും ഭദ്ര ദേവിയുടെ അനുഗ്രഹം നൽകും.',

    // About
    historyTab: 'ചരിത്രവും ഐതിഹ്യവും',
    architectureTab: 'ക്ഷേത്ര വാസ്തുശില്പം',
    trustTab: 'ഭരണസമിതി & ട്രസ്റ്റ്',
    etiquetteTab: 'ക്ഷേത്ര ആചാരങ്ങൾ',
    divineOrigin: 'ദിവ്യ സാന്നിധ്യം • ചരിത്രവും ഐതിഹ്യവും',
    divinePresenceTitle: 'തുറയിൽക്കുന്നിലെ ശ്രീ ഭദ്രകാളി സാന്നിധ്യം',
    divinePresenceSubtitle: 'തലമുറകളായി ഒഴുകുന്ന മാതൃവാത്സല്യവും ദൈവിക ചൈതന്യവും',
    quoteText: '"സർവ്വാഭീഷ്ടവരദായിനിയായ ശ്രീ ഭദ്രകാളിയുടെ അനുഗ്രഹവർഷം തുറയിൽക്കുന്നിലെ പുണ്യഭൂമിയിൽ തലമുറകളായി ഒഴുകുന്നു."',
    quoteAuthor: '— വിശ്വാസ പാരമ്പര്യം',
    shieldTitle: 'സർവ്വ രക്ഷാ കവചം',
    shieldDesc: 'ഭദ്രകാളി അമ്മ ഭക്തരെ എല്ലാ അപകടങ്ങളിൽ നിന്നും രോഗങ്ങളിൽ നിന്നും ഭയങ്ങളിൽ നിന്നും കാത്തുരക്ഷിക്കുന്നു.',
    wishesTitle: 'സർവ്വാഭീഷ്ട സിദ്ധി',
    wishesDesc: 'ആരോഗ്യം, വിവാഹം, അഭിവൃദ്ധി എന്നിവയ്ക്കുള്ള ആത്മാർത്ഥ പ്രാർത്ഥനകൾ ഫലവത്താകുന്നു.',
    templeSanctumLocation: 'തുറയിൽക്കുന്ന്, കരുനാഗപ്പള്ളി',
    quickFacts: 'ക്ഷേത്ര വിവരങ്ങൾ',
    presidingDeityLabel: 'പ്രധാന പ്രതിഷ്ഠ',
    auspiciousStarLabel: 'പ്രതിഷ്ഠാ നക്ഷത്രം',
    annualFestivalLabel: 'വാർഷിക മഹോത്സവം',
    srikovilTitle: 'ശ്രീകോവിൽ',
    srikovilDesc: 'പരമ്പരാഗത കേരള തച്ചുശാസ്ത്ര പ്രകാരം നിർമ്മിച്ചത്. പ്രകൃതിദത്ത വെട്ടുകല്ലും ചെമ്പ് മേൽക്കൂരയും ഉള്ള ചതുര ശ്രീകോവിൽ ദൈവിക ഊർജ്ജം കാത്തുസൂക്ഷിക്കുന്നു.',
    chuttambalamTitle: 'ചുറ്റമ്പലവും ആനപ്പന്തലും',
    chuttambalamDesc: 'ദീപാരാധന സമയത്ത് പ്രകാശിക്കുന്ന വിളക്കുകളുടെ നിരകൾ നിറഞ്ഞ ചുറ്റമ്പലം. മേളങ്ങൾക്കും എഴുന്നള്ളത്തിനും ഭക്തർക്ക് ഇടം നൽകുന്ന ആനപ്പന്തൽ.',
    sarpaKavuTitle: 'പവിത്രമായ സർപ്പക്കാവ്',
    sarpaKavuDesc: 'പവിത്ര വൃക്ഷങ്ങളും ഔഷധ സസ്യങ്ങളും നിറഞ്ഞ പുരാതന കാവ്. നാഗരാജാവിനും നാഗയക്ഷിക്കും നൂറും പാലും മഞ്ഞൾപ്പൊടിയും സമർപ്പിക്കുന്നു.',
    thidappallyTitle: 'തിടപ്പള്ളിയും ഊട്ടുപുരയും',
    thidappallyDesc: 'ശുദ്ധമായ നെയ്യും ശർക്കരയും ഉപയോഗിച്ച് കേരള വൈദിക വിധിപ്രകാരം കടുംപായസവും നിവേദ്യങ്ങളും തയ്യാറാക്കുന്ന പവിത്രമായ അടുക്കള.',
    trustIntroTitle: 'ഭരണസമിതി & ക്ഷേത്ര ട്രസ്റ്റ്',
    trustIntroDesc: 'പുരാതന ആചാരങ്ങൾ സംരക്ഷിക്കുന്നതിനും ഉത്സവങ്ങൾ നടത്തുന്നതിനും നിത്യ അന്നദാനം നടത്തുന്നതിനും സമർപ്പിതമായ രജിസ്ട്രേഡ് ട്രസ്റ്റ്.',
    trustRegLabel: 'ട്രസ്റ്റ് രജിസ്ട്രേഷൻ',
    trustRegVal: 'രജിസ്ട്രേഡ് പബ്ലിക് റിലീജിയസ് ട്രസ്റ്റ്',
    trustOfficeLabel: 'ഓഫീസ് വിലാസം',
    contactPhoneLabel: 'ഫോൺ നമ്പർ',
    officialBankDetails: 'ഔദ്യോഗിക ബാങ്ക് വിവരങ്ങൾ',
    donateToTrust: 'E-കാണിക്ക സമർപ്പിക്കുക',
    contactOffice: 'ഓഫീസുമായി ബന്ധപ്പെടുക',
    dressCodeTitle: 'ക്ഷേത്ര ദർശന വസ്ത്രധാരണ രീതി',
    dressCodeIntro: 'ക്ഷേത്രത്തിൽ പ്രവേശിക്കുമ്പോൾ പരമ്പരാഗത വസ്ത്രധാരണം പാലിക്കാൻ ഭക്തരോട് അഭ്യർത്ഥിക്കുന്നു:',
    dressMenLabel: 'പുരുഷന്മാർ',
    dressMenVal: 'പരമ്പരാഗത മുണ്ട് (കച്ചമുണ്ടു് / കസവുമുണ്ടു്). ശ്രീകോവിലിന് മുന്നിൽ ഷർട്ട് അഴിക്കേണ്ടതാണ്.',
    dressWomenLabel: 'സ്ത്രീകൾ',
    dressWomenVal: 'സാരി, സെറ്റ് മുണ്ട്, സൽവാർ കമ്മീസ് അല്ലെങ്കിൽ പരമ്പരാഗത മാന്യമായ വസ്ത്രങ്ങൾ.',
    dressKidsLabel: 'കുട്ടികൾ',
    dressKidsVal: 'പരമ്പരാഗത മാന്യമായ വസ്ത്രങ്ങൾ.',
    customsTitle: 'ക്ഷേത്ര ചിട്ടവട്ടങ്ങൾ',
    customs1: 'ക്ഷേത്ര കവാടത്തിന് പുറത്തുള്ള കൗണ്ടറിൽ പാദരക്ഷകൾ അഴിച്ചുവെക്കുക.',
    customs2: 'പ്രാർത്ഥനാപൂർവ്വം പ്രഭാത/സന്ധ്യാ പ്രദക്ഷിണം നടത്തുക.',
    customs3: 'ശ്രീകോവിലിനുള്ളിൽ ഫോട്ടോഗ്രാഫിയും വീഡിയോയും കർശനമായി നിരോധിച്ചിരിക്കുന്നു.',
    customs4: 'ക്ഷേത്ര പരിസരത്ത് മൊബൈൽ ഫോണുകൾ സൈലന്റ് മോഡിൽ വെക്കുക.',
    customs5: 'ക്ഷേത്ര ശുചിത്വം പാലിക്കുകയും സർപ്പക്കാവിലെ വിശുദ്ധ സസ്യങ്ങളെ സംരക്ഷിക്കുകയും ചെയ്യുക.',
    planVisit: 'ക്ഷേത്ര സന്ദർശനം ആസൂത്രണം ചെയ്യുകയാണോ? ദർശന സമയം പരിശോധിച്ച് വഴിപാടുകൾ മുൻകൂട്ടി ബുക്ക് ചെയ്യാം.',

    // Deities
    specialDaysLabel: 'വിശേഷ ദിവസങ്ങൾ',
    keyOfferingsLabel: 'പ്രധാന വഴിപാടുകൾ',
    bookOffering: 'വഴിപാട് സമർപ്പിക്കുക',
    darshanTimingsBtn: 'ദർശന സമയം',
    allShrines: 'എല്ലാ സന്നിധികളും',
    deitySplendor: 'ദിവ്യ പ്രതിഷ്ഠാ വൈഭവം',
    dhyanaSloka: 'ധ്യാന ശ്ലോകം',
    bookOfferingsForDeity: 'വഴിപാടുകൾ ബുക്ക് ചെയ്യുക',
    specialLabel: 'വിശേഷ ദിവസം:',

    // Darshan
    templeOpen: 'നട തുറന്നിരിക്കുന്നു',
    templeClosed: 'നട അടച്ചിരിക്കുന്നു',
    darshanAvailable: 'ഭക്തജനങ്ങൾക്ക് ദർശന സൗകര്യം ഉണ്ട്',
    nextDarshanSoon: 'അടുത്ത ദർശന സമയം ഉടൻ',
    morningSession: 'പ്രഭാതം',
    eveningSession: 'സന്ധ്യ & രാത്രി',
    specialPoojasDays: 'പ്രത്യേക പൂജാ ദിനങ്ങൾ',
    monthlyObservances: 'മാസ വിശേഷങ്ങൾ',
    bookSpecialPoojaBirthStar: 'നിങ്ങളുടെ ജന്മനക്ഷത്രത്തിൽ പ്രത്യേക പൂജകൾ ബുക്ക് ചെയ്യാം',
    bookSpecialPoojaDesc: 'ദിവസേനയുള്ള അർച്ചന, പുഷ്പാഞ്ജലി, പായസ നിവേദ്യങ്ങൾ എന്നിവ മുൻകൂട്ടി ബുക്ക് ചെയ്യാം.',
    timeRemClosesAfternoon: (h, m) => `ഉച്ചയ്ക്ക് നട അടയ്ക്കാൻ ${h > 0 ? `${h} മണിക്കൂർ ` : ''}${m} മിനിറ്റ് ബാക്കി`,
    timeRemClosesNight: (h, m) => `രാത്രി നട അടയ്ക്കാൻ ${h > 0 ? `${h} മണിക്കൂർ ` : ''}${m} മിനിറ്റ് ബാക്കി`,
    timeRemOpensMorning: (h, m) => `പ്രഭാത നട തുറക്കാൻ ${h > 0 ? `${h} മണിക്കൂർ ` : ''}${m} മിനിറ്റ് ബാക്കി (5:30 AM)`,
    timeRemOpensEvening: (h, m) => `സന്ധ്യാ നട തുറക്കാൻ ${h > 0 ? `${h} മണിക്കൂർ ` : ''}${m} മിനിറ്റ് ബാക്കി (5:00 PM)`,
    timeRemOpensTomorrow: 'പ്രഭാത നട നാളെ രാവിലെ 5:30 ന് തുറക്കും',

    // Vazhipadu
    searchPlaceholder: 'വഴിപാട് തിരയുക (ഉദാ: കടുംപായസം, പുഷ്പാഞ്ജലി, ഗണപതി ഹോമം)...',
    allDeities: 'എല്ലാ പ്രതിഷ്ഠകളും',
    showingOfferings: 'കാണിക്കുന്നത്',
    divineOfferings: 'ദിവ്യ വഴിപാടുകൾ',
    resetFilters: 'ഫിൽറ്റർ മായ്ക്കുക',
    poojaCart: 'വഴിപാട് കുട്ട',
    cartEmpty: 'നിങ്ങളുടെ വഴിപാട് കുട്ട ഒഴിഞ്ഞിരിക്കുന്നു.',
    cartEmptyHint: 'ബുക്കിംഗ് തുടരാൻ കാറ്റലോഗിൽ നിന്ന് വഴിപാടുകൾ തിരഞ്ഞെടുക്കുക.',
    totalAmount: 'ആകെ തുക',
    proceedBooking: 'തുടരുക',
    confirmBooking: 'ബുക്കിംഗ് സ്ഥിരീകരിക്കുക',
    devoteeName: 'ഭക്തന്റെ പേര്',
    birthStar: 'ജന്മ നക്ഷത്രം',
    poojaDate: 'വഴിപാട് തീയതി',
    mobileNumber: 'ഫോൺ നമ്പർ',
    emailAddress: 'ഇമെയിൽ വിലാസം',
    specialSankalpam: 'പ്രത്യേക സങ്കൽപ്പം / പ്രാർത്ഥന',
    postalPrasadam: 'തപാൽ വഴി പ്രസാദം അയക്കുക',
    postalAddress: 'പൂർണ്ണ തപാൽ വിലാസം (പിൻ കോഡ് സഹിതം)',
    paymentMode: 'പണമടയ്ക്കൽ രീതി',
    upiPayment: 'UPI / Google Pay / PhonePe',
    counterPayment: 'ക്ഷേത്ര കൗണ്ടറിൽ നേരിട്ട് അടയ്ക്കുക',
    printReceipt: 'രസീത് പ്രിന്റ് ചെയ്യുക',
    close: 'അടയ്ക്കുക',
    noOfferingsMatch: 'നിങ്ങൾ തിരഞ്ഞ വഴിപാടുകൾ ലഭ്യമല്ല.',
    clearAllFilters: 'എല്ലാ ഫിൽറ്ററുകളും മാറ്റുക',
    bookingDetails: 'ഭക്തജന വിവരങ്ങൾ',
    bookingToken: 'ബുക്കിംഗ് ടോക്കൺ',
    devoteeLabel: 'ഭക്തൻ:',
    starLabel: 'നാൾ:',
    dateLabel: 'വഴിപാട് തീയതി:',
    phoneLabel: 'ഫോൺ:',
    paymentModeLabel: 'പണമടയ്ക്കൽ രീതി:',
    bookedAtLabel: 'ബുക്ക് ചെയ്ത സമയം:',
    poojaOfferingHeader: 'വഴിപാട്',
    deityHeader: 'ദേവത',
    qtyHeader: 'എണ്ണം',
    amountHeader: 'തുക',
    totalPaidPayable: 'ആകെ തുക:',
    postalPrasadamAddr: 'തപാൽ പ്രസാദ വിലാസം:',
    officialUpiHint: 'ക്ഷേത്ര കൗണ്ടറിൽ ഈ ടോക്കൺ സ്ക്രീൻഷോട്ടോ രസീതോ കാണിക്കുക.',

    // Festivals
    annualFestival: 'വാർഷിക മഹോത്സവം',
    donateFestival: 'ഉത്സവ സംഭാവന സമർപ്പിക്കുക',
    bookFestivalOffering: 'ഉത്സവ വഴിപാടുകൾ ബുക്ക് ചെയ്യുക',
    festivalsHighlights: 'പ്രത്യേകതകൾ',
    sponsorDay: 'ഒരു ദിവസം സ്പോൺസർ ചെയ്യുക',
    festivalSponsorship: 'ഉത്സവ സേവകളും അന്നദാന പങ്കാളിത്തവും',
    festivalSponsorshipDesc: 'ആയിരക്കണക്കിന് ഭക്തർ പങ്കെടുക്കുന്ന അന്നദാനം, തലപ്പൊലി ദീപങ്ങൾ, ദീപാലങ്കാരം, പുഷ്പാഞ്ജലി എന്നിവ ഉൾപ്പെടെയുള്ള ഉത്സവ ദിവസങ്ങൾ ഭക്തർക്ക് സ്പോൺസർ ചെയ്യാം.',
    bookPoojas: 'പൂജകൾ ബുക്ക് ചെയ്യുക',

    // Gallery
    allVisuals: 'എല്ലാ ദൃശ്യങ്ങളും',
    sanctumCat: 'ശ്രീകോവിൽ',
    festivalsCat: 'ഉത്സവങ്ങൾ',
    sarpaKavuCat: 'സർപ്പക്കാവ്',
    architectureCat: 'വാസ്തുശില്പം',

    // Kanikka/Donation
    annadanamScheme: 'നിത്യ അന്നദാന പദ്ധതി',
    renovationScheme: 'ക്ഷേത്ര പുനരുദ്ധാരണ ഫണ്ട്',
    deepamScheme: 'നിത്യ ദീപ & എണ്ണ സമർപ്പണ ഫണ്ട്',
    generalScheme: 'ജനറൽ E-കാണിക്ക',
    customAmount: 'മറ്റൊരു തുക നൽകുക',
    donorName: 'ഭക്തൻ / ദാതാവിന്റെ പേര്',
    copyBankDetails: 'ബാങ്ക് വിവരങ്ങൾ പകർത്തുക',
    bankDetailsCopied: 'ബാങ്ക് വിവരങ്ങൾ പകർത്തി!',
    directUpi: 'UPI നേരിട്ട് അടയ്ക്കുക',
    taxNote: 'ഭരണത്തേരിൽ ക്ഷേത്ര ട്രസ്റ്റിലേക്കുള്ള സംഭാവനകൾ 80G വകുപ്പ് പ്രകാരം നികുതി ഇളവിന് അർഹമാണ്.',
    proceedDonate: 'കാണിക്ക സമർപ്പിക്കുക',
    offeringAmountAndDetails: 'കാണിക്ക തുക & ഭക്തന്റെ വിവരങ്ങൾ',
    selectAmountHint: 'നിങ്ങൾ സമർപ്പിക്കാൻ ആഗ്രഹിക്കുന്ന തുക തിരഞ്ഞെടുക്കുക:',
    addressState: 'വിലാസം / സംസ്ഥാനം',
    panCard: 'പാൻ കാർഡ് (80G നികുതി ഇളവിനായി)',
    offeringAmountLabel: 'കാണിക്ക തുക:',
    officialBankAccount: 'ക്ഷേത്ര ഔദ്യോഗിക ബാങ്ക് അക്കൗണ്ട്',
    bankNameLabel: 'ബാങ്ക്:',
    branchLabel: 'ബ്രാഞ്ച്:',
    accountNameLabel: 'അക്കൗണ്ട് ഉടമ:',
    accountNumberLabel: 'അക്കൗണ്ട് നമ്പർ:',
    ifscCodeLabel: 'IFSC കോഡ്:',
    upiAppsHint: 'ഗൂഗിൾ പേ, ഫോൺപേ, പേടിഎം, ഭീം എന്നിവ വഴി പണമടയ്ക്കാം.',
    eKanikkaReceipt: 'E-കാണിക്ക രസീത്',
    blessingQuote: '"ഭഗവതിയുടെ അനുഗ്രഹവർഷം നിങ്ങളിലും കുടുംബത്തിലും സദാ ഉണ്ടായിരിക്കട്ടെ."',
    done: 'പൂർത്തിയായി',

    // Contact
    locationTitle: 'ക്ഷേത്ര സ്ഥാനം',
    phonehelpline: 'ഫോൺ ഹെൽപ്‌ലൈൻ',
    emailAddress2: 'ഇമെയിൽ',
    officeHours: 'ഓഫീസ് സമയം',
    howToReach: 'ഭരണത്തേരിൽ ക്ഷേത്രത്തിൽ എങ്ങനെ എത്തിച്ചേരാം?',
    byTrain: 'ട്രെയിനിൽ',
    byBus: 'ബസ്സിൽ (KSRTC)',
    byRoad: 'റോഡ് (NH-66)',
    byAir: 'വിമാനത്തിൽ',
    byTrainDesc: 'എല്ലാ പ്രധാന എക്സ്പ്രസ് ട്രെയിനുകൾക്കും കരുനാഗപ്പള്ളിയിൽ സ്റ്റോപ്പുണ്ട്. സ്റ്റേഷനിൽ നിന്ന് മുഴുവൻ സമയവും ഓട്ടോറിക്ഷകളും ടാക്സികളും ലഭ്യമാണ്.',
    byBusDesc: 'കെ.എസ്.ആർ.ടി.സി സൂപ്പർഫാസ്റ്റ്, ഫാസ്റ്റ് പാസഞ്ചർ ബസുകൾ കരുനാഗപ്പള്ളിയെ മറ്റ് പ്രധാന നഗരങ്ങളുമായി ബന്ധിപ്പിക്കുന്നു.',
    byRoadDesc: 'ദേശീയപാത 66 കരുനാഗപ്പള്ളി ജംഗ്ഷനിൽ നിന്ന് തുറയിൽക്കുന്ന് ലിങ്ക് റോഡ് വഴി നേരിട്ട് ക്ഷേത്ര കവാടത്തിലെത്താം.',
    byAirDesc: 'തിരുവനന്തപുരം അന്താരാഷ്ട്ര വിമാനത്താവളത്തിൽ നിന്ന് ദേശീയപാത 66 വഴിയും ട്രെയിൻ വഴിയും കരുനാഗപ്പള്ളിയിലെത്താം.',
    devoteesEnquiry: 'ഭക്തജന അന്വേഷണം',
    fullName: 'പൂർണ്ണ നാമം',
    mobileNo: 'ഫോൺ നമ്പർ',
    subject: 'വിഷയം',
    messageLabel: 'സന്ദേശം',
    sendEnquiry: 'സന്ദേശം അയക്കുക',
    messageSent: 'സന്ദേശം വിജയകരമായി ലഭിച്ചു!',
    messageSentDesc: 'ബന്ധപ്പെട്ടതിന് നന്ദി. ക്ഷേത്ര ഓഫീസ് ഉടൻ മറുപടി നൽകും. ദേവി അനുഗ്രഹിക്കട്ടെ.',
    templeLocationMap: 'ക്ഷേത്ര ലൊക്കേഷൻ മാപ്പ്',
    directionsLabel: 'വഴികാട്ടി:',
    travelDirectionsText: 'കരുനാഗപ്പള്ളി ടൗണിൽ നിന്ന് തുറയിൽക്കുന്ന് ലിങ്ക് റോഡ് വഴി മുന്നോട്ട് പോകുക. കരുനാഗപ്പള്ളി കെ.എസ്.ആർ.ടി.സി സ്റ്റാൻഡിൽ നിന്നും റെയിൽവേ സ്റ്റേഷനിൽ നിന്നും നേരിട്ട് ക്ഷേത്രത്തിലേക്ക് ഓട്ടോറിക്ഷകളും ടാക്സികളും ലഭ്യമാണ്.',

    // Footer
    quickLinks: 'ഉപയോഗപ്രദ ലിങ്കുകൾ',
    darshanFooter: 'ദർശന സമയം',
    contactFooter: 'ഹെൽപ്‌ലൈൻ',
    copyright: `© ${new Date().getFullYear()} ഭരണത്തേരിൽ ശ്രീ ഭദ്ര ഭഗവതി ക്ഷേത്ര ട്രസ്റ്റ്. എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.`,
    footerBlessing: 'ഓം ശ്രീ ഭദ്രകാള്യൈ നമഃ • സർവ്വത്ര ശാന്തിർഭവതു',

    // Sections
    sacredShrinesses: 'പവിത്ര സന്നിധികളും ദൈവിക സാന്നിധ്യങ്ങളും',
    allShrinesBtn: 'ക്ഷേത്രത്തിലെ എല്ലാ സന്നിധികളും',
    pilgrimage: 'തീർത്ഥാടന വഴികാട്ടി',
    selected: 'തിരഞ്ഞെടുത്തു',
    select: 'തിരഞ്ഞെടുക്കുക',

    // Units and Timers
    daysUnit: 'ദിവസം',
    hoursUnit: 'മണിക്കൂർ',
    minutesUnit: 'മിനിറ്റ്',
    secondsUnit: 'സെക്കൻഡ്',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] || translations['en'][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
